---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 24h
  url: oci://ghcr.io/traefik/helm/traefik
  ref:
    tag: 41.6.0
    digest: sha256:9e91c00c5f3578e9f646debed77a4cd8f034879989869786523dcad74466a931
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: traefik
  values:
    ingressClass:
      enabled: true
      isDefaultClass: true
      name: traefik
    ports:
      web:
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
