---

- name: Create registry storage directory
  file:
    state: directory
    path: "{{ registry_dir }}"

- name: Create local registry container
  docker_container:
    name: registry
    image: "registry:2.8"
    ports:
      "{{ registry_port }}:5000"
    volumes:
      - "{{ registry_dir }}:/var/lib/registry/"
    container_default_behavior: compatibility
    restart_policy: always
