---

# "echo 'Hey' 1>&2",
# "sleep 60",
# "sudo apt-get update",
# "sudo apt-get install unzip -y",
# "curl -L https://releases.hashicorp.com/vault/1.3.2/vault_1.3.2_linux_amd64.zip -o vault.zip",
# "unzip vault.zip",
# "sudo chown root:root vault",
# "mv vault /usr/local/bin/",
# "rm -f vault.zip"

- name: 'Install & Configure Vault'
  hosts: default
  vars_files:
    - variables.yml
  become: true

  tasks:
    - name: Update package cache
      package:
        update_cache: yes
    
    - name: Install dependencies
      package:
        name:
          - unzip

    - name: Download Vault binary
      get_url:
        url: https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip
        dest: /tmp/vault_{{ vault_version }}_linux_amd64.zip
        checksum: "{{ vault_checksum }}"
      register: vault_download

    - name: "Unzip vault archive"
      unarchive:
        src: "{{ vault_download.dest }}"
        dest: /usr/local/bin
        copy: no
        mode: 0755

    - name: Create systemctl service
      debug:
        msg: "hey!"