---

- name: Set up netbox data directories
  ansible.builtin.file:
    path: "{{ netbox_dir }}/{{ item }}"
    state: directory
    mode: 0775
  with_items:
    - media
    - db
    - redis

- name: Create netbox shared network
  community.general.docker_network:
    name: netbox_network

- name: Netbox - Postgres DB container
  community.general.docker_container:
    name: netbox-postgres
    image: postgres:14-alpine
    pull: true
    networks:
      - name: netbox_network
        aliases:
          - postgres
    network_mode: default
    volumes:
      - "{{ netbox_dir }}/db:/data"
    env:
      POSTGRES_USER: "{{ netbox_db_user }}"
      POSTGRES_PASSWORD: "{{ netbox_db_pass }}"
      PGDATA: "/data"
    restart_policy: unless-stopped
    container_default_behavior: compatibility

- name: Netbox - Redis container
  community.general.docker_container:
    name: netbox-redis
    image: redis:6.2-alpine
    pull: true
    networks:
      - name: netbox_network
        aliases:
          - redis
    network_mode: default
    volumes:
      - "{{ netbox_dir }}/redis:/data"
    command: "redis-server --appendonly yes"
    restart_policy: always
    container_default_behavior: compatibility

- name: Netbox - Redis cache container
  community.general.docker_container:
    name: netbox-redis-cache
    image: redis:6.2-alpine
    pull: true
    networks:
      - name: netbox_network
        aliases:
          - redis-cache
    network_mode: default
    restart_policy: always
    container_default_behavior: compatibility

# TODO: change logging level to be less verbose
- name: Netbox - App container
  community.general.docker_container:
    name: netbox-app
    image: netboxcommunity/netbox:v3.1
    pull: true
    ports:
      - "8080"
    networks:
      - name: netbox_network
    network_mode: default
    volumes:
      # default configuration scripts are included with dockerfile
      # see https://github.com/netbox-community/netbox-docker/blob/release/docker-compose.yml
      # for details of the folders, should any of the files need modifying.
      - "{{ netbox_dir }}/app/media:/opt/netbox/netbox/media"
    env:
      SECRET_KEY: "{{ netbox_secret_key }}"
      DB_HOST: postgres
      DB_NAME: netbox
      DB_USER: "{{ netbox_db_user }}"
      DB_PASSWORD: "{{ netbox_db_pass }}"
      REDIS_CACHE_DATABASE: "1"
      REDIS_CACHE_HOST: "redis-cache"
      REDIS_CACHE_SSL: "false"
      REDIS_DATABASE: "0"
      REDIS_HOST: "redis"
      REDIS_SSL: "false"
      LOGIN_REQUIRED: "true"
    restart_policy: unless-stopped
    container_default_behavior: compatibility
    labels:
      traefik.enable: "true"
      traefik.http.routers.netbox.rule: "Host(`netbox.{{ homelab_domain }}`)"
      traefik.http.routers.netbox.entrypoints: "websecure"
      traefik.http.routers.netbox.tls: "true"
