---
- name: Set up vaultwarden data directories
  ansible.builtin.file:
    path: "{{ vaultwarden_dir }}"
    state: directory
    mode: "0775"

- name: Vaultwarden - App contrainer
  community.general.docker_container:
    name: vaultwarden-app
    image: vaultwarden/server:1.32.1-alpine@sha256:a61afd8b8b9c8f15ef642cf9338e07d7ea4b8ca3af75022a6debb287a40cdc5b
    pull: true
    ports:
      - "80"
    volumes:
      - "{{ vaultwarden_dir }}/:/data/"
    env:
      ADMIN_TOKEN: "{{ vaultwarden_admin_token }}"
    restart_policy: unless-stopped
    container_default_behavior: compatibility
    labels:
      traefik.enable: "true"
      traefik.http.routers.vaultwarden.rule: "Host(`vw.{{ homelab_domain }}`)"
      traefik.http.routers.vaultwarden.entrypoints: "websecure"
      traefik.http.routers.vaultwarden.tls: "true"
