---
- name: Set up plex data directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  with_items:
    - "{{ plex_dir }}/config"
    - "{{ media_dir }}/media"

- name: Create Plex server container
  community.general.docker_container:
    name: plex-app
    image: linuxserver/plex:1.41.3@sha256:3d2ed27abb4f72038705c3e0c3d40ff89821a0c66d43e55125873de127197d25
    pull: true
    image_name_mismatch: recreate
    network_mode: default
    ports:
      - "32400" # Web interface
      - "1900/udp" # Plex DLNA (Not used)
      - 3005:3005 # Plex Companion
      - 5353:5353/udp # Bonjour/Avahi network discovery
      - 8324:8324 # Plex Companion
      - 32410:32410/udp # GDM network discovery
      - 32412:32412/udp # GDM network discovery
      - 32413:32413/udp # GDM network discovery
      - 32414:32414/udp # GDM network discovery
      - "32469" # Plex DLNA (Not used)
    volumes:
      - "{{ plex_dir }}/config:/config"
      - "{{ media_dir }}/media:/data/media"
    env:
      PUID: "1000"
      PGID: "1000"
      VERSION: docker
      PLEX_CLAIM: "{{ plex_claim_token }}"
    restart_policy: unless-stopped
    container_default_behavior: compatibility
    labels:
      traefik.enable: "true"
      traefik.http.routers.plex.rule: "Host(`tv.{{ homelab_domain }}`)"
      traefik.http.routers.plex.entrypoints: "websecure"
      traefik.http.routers.plex.tls: "true"
      traefik.http.services.plex.loadbalancer.server.port: "32400"
