---
- name: Create registry storage directory
  ansible.builtin.file:
    state: directory
    path: "{{ registry_dir }}"
    mode: "0775"

- name: Create local registry container
  community.general.docker_container:
    name: registry
    image: "registry:3.0@sha256:1fc7de654f2ac1247f0b67e8a459e273b0993be7d2beda1f3f56fbf1001ed3e7"
    pull: true
    image_name_mismatch: recreate
    ports: "{{ registry_port }}:5000"
    volumes:
      - "{{ registry_dir }}:/var/lib/registry/"
    container_default_behavior: compatibility
    restart_policy: always
