---
- name: Create registry storage directory
  ansible.builtin.file:
    state: directory
    path: "{{ registry_dir }}"
    mode: "0775"

- name: Create local registry container
  community.general.docker_container:
    name: registry
    image: "registry:2.8@sha256:e54fc7162fb357c4476ffc09b5b8656c9cd113015386f2393d430a7379419aa0"
    pull: true
    image_name_mismatch: recreate
    ports: "{{ registry_port }}:5000"
    volumes:
      - "{{ registry_dir }}:/var/lib/registry/"
    container_default_behavior: compatibility
    restart_policy: always
