---
- name: Create registry storage directory
  ansible.builtin.file:
    state: directory
    path: "{{ registry_dir }}"
    mode: "0775"

- name: Create local registry container
  community.general.docker_container:
    name: registry
    image: "registry:2.8@sha256:a3d8aaa63ed8681a604f1dea0aa03f100d5895b6a58ace528858a7b332415373"
    pull: true
    image_name_mismatch: recreate
    ports: "{{ registry_port }}:5000"
    volumes:
      - "{{ registry_dir }}:/var/lib/registry/"
    container_default_behavior: compatibility
    restart_policy: always
