---
- name: Create registry storage directory
  ansible.builtin.file:
    state: directory
    path: "{{ registry_dir }}"
    mode: "0775"

- name: Create local registry container
  community.general.docker_container:
    name: registry
    image: "registry:2.8@sha256:543dade69668e02e5768d7ea2b0aa4fae6aa7384c9a5a8dbecc2be5136079ddb"
    ports: "{{ registry_port }}:5000"
    volumes:
      - "{{ registry_dir }}:/var/lib/registry/"
    container_default_behavior: compatibility
    restart_policy: always
