---

- name: Set up nextcloud data directories
  file:
    path: "{{ nextcloud_dir }}/{{ item }}"
    state: directory
  with_items:
    - db
    - data

- name: Copy nextcloud Dockerfile to host
  template:
    src: "{{ item }}"
    dest: "{{ nextcloud_dir }}/{{ item }}"
  with_items:
    - Dockerfile
    - .dockerignore
  register: nextcloud_dockerfile

- name: Build nextcloud image with smbclient installed
  docker_image:
    name: "{{ registry_host }}:{{ registry_port }}/nextcloud"
    tag: "{{ nextcloud_version }}-smb"
    build:
      pull: true
      path: "{{ nextcloud_dir }}"
    push: true
    source: build
    force_source: "{{ nextcloud_dockerfile.changed }}"
  register: nextcloud_image

- name: Create nextcloud network
  docker_network:
    name: nextcloud_network

- name: Nextcloud - MariaDB container
  docker_container:
    name: nextcloud-mariadb
    image: mariadb:10.8
    pull: true
    networks:
      - name: nextcloud_network
        aliases:
          - mariadb
    network_mode: default
    volumes:
      - "{{ nextcloud_dir }}/db:/var/lib/mysql"
    env:
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "{{ nextcloud_sql_user }}"
      MYSQL_PASSWORD: "{{ nextcloud_sql_pass }}"
      MYSQL_ROOT_PASSWORD: "{{ nextcloud_sql_secret }}"
    command: --skip-innodb-read-only-compressed
    restart_policy: unless-stopped
    container_default_behavior: compatibility

- name: Nextcloud - Redis container
  docker_container:
    name: nextcloud-redis
    image: redis:6.2-alpine
    networks:
      - name: nextcloud_network
        aliases:
          - redis
    network_mode: default
    pull: true
    restart_policy: always
    container_default_behavior: compatibility

- name: Nextcloud - Cron container
  docker_container:
    name: nextcloud-cron
    image: "{{ registry_host }}:{{ registry_port }}/nextcloud:{{ nextcloud_version }}-smb"
    recreate: "{{ nextcloud_image.changed }}"
    networks:
      - name: nextcloud_network
        aliases:
          - cron
    network_mode: default
    volumes:
      - "{{ nextcloud_dir }}/data:/var/www/html:rw"
    entrypoint: "/cron.sh"
    restart_policy: always
    container_default_behavior: compatibility

- name: Nextcloud - App container
  docker_container:
    name: nextcloud-app
    image: "{{ registry_host }}:{{ registry_port }}/nextcloud:{{ nextcloud_version }}-smb"
    recreate: "{{ nextcloud_image.changed }}"
    networks:
      - name: nextcloud_network
        aliases:
          - app
    network_mode: default
    volumes:
      - "{{ nextcloud_dir }}/data:/var/www/html:rw"
    ports:
      - "80"
    env:
      MYSQL_HOST: "mariadb"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "{{ nextcloud_sql_user }}"
      MYSQL_PASSWORD: "{{ nextcloud_sql_pass }}"
      REDIS_HOST: redis
      NEXTCLOUD_TRUSTED_DOMAINS: "files.{{ homelab_domain }}"
    restart_policy: unless-stopped
    container_default_behavior: compatibility
    labels:
      traefik.enable: "true"
      traefik.http.routers.nextcloud.rule: "Host(`files.{{ homelab_domain }}`)"
      traefik.http.routers.nextcloud.entrypoints: "websecure"
      traefik.http.routers.nextcloud.tls: "true"
      traefik.http.middlewares.nextcloud-redirectregex.redirectRegex.permanent: "true"
      traefik.http.middlewares.nextcloud-redirectregex.redirectRegex.regex: "https://(.*)/.well-known/(card|cal)dav"
      traefik.http.middlewares.nextcloud-redirectregex.redirectRegex.replacement: "https://${1}/remote.php/dav/"
