---
- name: Set up nextcloud data directories
  ansible.builtin.file:
    path: "{{ nextcloud_dir }}/{{ item }}"
    state: directory
    mode: "0775"
  with_items:
    - db
    - data

- name: Create nextcloud network
  community.general.docker_network:
    name: nextcloud_network

- name: Nextcloud - MariaDB container
  community.general.docker_container:
    name: nextcloud-mariadb
    image: mariadb:10.11@sha256:34adebbac117c8ce649040e009f520fb79e577c68cc4e57debdf91befa53907f
    pull: true
    image_name_mismatch: recreate
    networks:
      - name: nextcloud_network
        aliases:
          - mariadb
    network_mode: default
    volumes:
      - "{{ nextcloud_dir }}/db:/var/lib/mysql"
    env:
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "{{ nextcloud_sql_user }}"
      MYSQL_PASSWORD: "{{ nextcloud_sql_pass }}"
      MYSQL_ROOT_PASSWORD: "{{ nextcloud_sql_secret }}"
    command: --skip-innodb-read-only-compressed
    restart_policy: unless-stopped
    container_default_behavior: compatibility

- name: Nextcloud - Redis container
  community.general.docker_container:
    name: nextcloud-redis
    image: redis:7.4-alpine@sha256:ee9e8748ace004102a267f7b8265dab2c618317df22507b89d16a8add7154273
    pull: true
    image_name_mismatch: recreate
    networks:
      - name: nextcloud_network
        aliases:
          - redis
    network_mode: default
    restart_policy: always
    container_default_behavior: compatibility

- name: Nextcloud - Cron container
  community.general.docker_container:
    name: nextcloud-cron
    image: "nextcloud:31.0.5-apache@sha256:ad8ee7888874d58442dd1f992bf575894926ec8aa0c43f88aca26543adaaa955"
    pull: true
    image_name_mismatch: recreate
    networks:
      - name: nextcloud_network
        aliases:
          - cron
    network_mode: default
    volumes:
      - "{{ nextcloud_dir }}/data:/var/www/html:rw"
    entrypoint: "/cron.sh"
    restart_policy: always
    container_default_behavior: compatibility

- name: Nextcloud - App container
  community.general.docker_container:
    name: nextcloud-app
    image: "nextcloud:31.0.5-apache@sha256:ad8ee7888874d58442dd1f992bf575894926ec8aa0c43f88aca26543adaaa955"
    pull: true
    image_name_mismatch: recreate
    networks:
      - name: nextcloud_network
        aliases:
          - app
    network_mode: default
    volumes:
      - "{{ nextcloud_dir }}/data:/var/www/html:rw"
    ports:
      - "80"
    env:
      MYSQL_HOST: "mariadb"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "{{ nextcloud_sql_user }}"
      MYSQL_PASSWORD: "{{ nextcloud_sql_pass }}"
      REDIS_HOST: redis
      NEXTCLOUD_TRUSTED_DOMAINS: "files.{{ homelab_domain }}"
    restart_policy: unless-stopped
    container_default_behavior: compatibility
    labels:
      traefik.enable: "true"
      traefik.http.routers.nextcloud.rule: "Host(`files.{{ homelab_domain }}`)"
      traefik.http.routers.nextcloud.entrypoints: "websecure"
      traefik.http.routers.nextcloud.tls: "true"
      traefik.http.middlewares.nextcloud-redirectregex.redirectRegex.permanent: "true"
      traefik.http.middlewares.nextcloud-redirectregex.redirectRegex.regex: "https://(.*)/.well-known/(card|cal)dav"
      traefik.http.middlewares.nextcloud-redirectregex.redirectRegex.replacement: "https://${1}/remote.php/dav/"
