---
- name: Set up nextcloud data directories
  ansible.builtin.file:
    path: "{{ nextcloud_dir }}/{{ item }}"
    state: directory
    mode: "0775"
  with_items:
    - db
    - data

- name: Create nextcloud network
  community.general.docker_network:
    name: nextcloud_network

- name: Nextcloud - MariaDB container
  community.general.docker_container:
    name: nextcloud-mariadb
    image: mariadb:10.11@sha256:5c2a279eacfa00bd4453b10569e36d8ee24331cdc09273df70c4dbd383c277b4
    pull: true
    image_name_mismatch: recreate
    networks:
      - name: nextcloud_network
        aliases:
          - mariadb
    network_mode: default
    volumes:
      - "{{ nextcloud_dir }}/db:/var/lib/mysql"
    env:
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "{{ nextcloud_sql_user }}"
      MYSQL_PASSWORD: "{{ nextcloud_sql_pass }}"
      MYSQL_ROOT_PASSWORD: "{{ nextcloud_sql_secret }}"
    command: --skip-innodb-read-only-compressed
    restart_policy: unless-stopped
    container_default_behavior: compatibility

- name: Nextcloud - Redis container
  community.general.docker_container:
    name: nextcloud-redis
    image: redis:7.4-alpine@sha256:c1e88455c85225310bbea54816e9c3f4b5295815e6dbf80c34d40afc6df28275
    pull: true
    image_name_mismatch: recreate
    networks:
      - name: nextcloud_network
        aliases:
          - redis
    network_mode: default
    restart_policy: always
    container_default_behavior: compatibility

- name: Nextcloud - Cron container
  community.general.docker_container:
    name: nextcloud-cron
    image: "nextcloud:29.0.9-apache@sha256:c67969c719138b0e09e107b453a9fc7a5cab13a3c30a2cc674e612547bb4d760"
    pull: true
    image_name_mismatch: recreate
    networks:
      - name: nextcloud_network
        aliases:
          - cron
    network_mode: default
    volumes:
      - "{{ nextcloud_dir }}/data:/var/www/html:rw"
    entrypoint: "/cron.sh"
    restart_policy: always
    container_default_behavior: compatibility

- name: Nextcloud - App container
  community.general.docker_container:
    name: nextcloud-app
    image: "nextcloud:29.0.9-apache@sha256:c67969c719138b0e09e107b453a9fc7a5cab13a3c30a2cc674e612547bb4d760"
    pull: true
    image_name_mismatch: recreate
    networks:
      - name: nextcloud_network
        aliases:
          - app
    network_mode: default
    volumes:
      - "{{ nextcloud_dir }}/data:/var/www/html:rw"
    ports:
      - "80"
    env:
      MYSQL_HOST: "mariadb"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "{{ nextcloud_sql_user }}"
      MYSQL_PASSWORD: "{{ nextcloud_sql_pass }}"
      REDIS_HOST: redis
      NEXTCLOUD_TRUSTED_DOMAINS: "files.{{ homelab_domain }}"
    restart_policy: unless-stopped
    container_default_behavior: compatibility
    labels:
      traefik.enable: "true"
      traefik.http.routers.nextcloud.rule: "Host(`files.{{ homelab_domain }}`)"
      traefik.http.routers.nextcloud.entrypoints: "websecure"
      traefik.http.routers.nextcloud.tls: "true"
      traefik.http.middlewares.nextcloud-redirectregex.redirectRegex.permanent: "true"
      traefik.http.middlewares.nextcloud-redirectregex.redirectRegex.regex: "https://(.*)/.well-known/(card|cal)dav"
      traefik.http.middlewares.nextcloud-redirectregex.redirectRegex.replacement: "https://${1}/remote.php/dav/"
