---
- name: Install app
  community.general.docker_container:
    name: hello
    image: nginxdemos/hello@sha256:f89cb9c05c54d591f5408b821b583beaf951f81733efd4062c1c61ce988ce682
    pull: true
    image_name_mismatch: recreate
    ports:
      - "80"
    container_default_behavior: compatibility
    restart_policy: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.hello.rule: "Host(`hello.{{ homelab_domain }}`)"
      traefik.http.routers.hello.entrypoints: websecure
      traefik.http.routers.hello.tls: "true"
