---
- name: Install app
  community.general.docker_container:
    name: hello
    image: nginxdemos/hello@sha256:b28d1e16c676896aaa98ed9c36d406cc4f4289558487f15e37e04354720f807a
    pull: true
    image_name_mismatch: recreate
    ports:
      - "80"
    container_default_behavior: compatibility
    restart_policy: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.hello.rule: "Host(`hello.{{ homelab_domain }}`)"
      traefik.http.routers.hello.entrypoints: websecure
      traefik.http.routers.hello.tls: "true"
