---
- name: Install app
  community.general.docker_container:
    name: hello
    image: nginxdemos/hello@sha256:91247f025eaa5e7677557d5a7ec8696708c40da724dc7f0b7b77c24498274147
    pull: true
    image_name_mismatch: recreate
    ports:
      - "80"
    container_default_behavior: compatibility
    restart_policy: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.hello.rule: "Host(`hello.{{ homelab_domain }}`)"
      traefik.http.routers.hello.entrypoints: websecure
      traefik.http.routers.hello.tls: "true"
