---
- name: Set up all services for homelab
  hosts: all

  vars_files:
    - vars.yml

  # install docker python library to be able to create docker containers
  vars:
    pip_install_packages:
      - name: docker

  roles:
    - role: geerlingguy.pip
      tags:
        - setup
    - role: geerlingguy.docker
      become: true
      tags:
        - setup

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true
      when: ansible_os_family == 'Debian'

    - name: Upgrade apt packages
      ansible.builtin.apt:
        upgrade: "yes"
      become: true
      when: ansible_os_family == 'Debian'

  tasks:
    - name: Set up main docker data directory
      ansible.builtin.file:
        path: "{{ data_dir }}"
        state: directory
        mode: "0755"

    - name: Set up local docker registry
      ansible.builtin.import_role:
        name: registry
      tags:
        - registry

    - name: Set up traefik reverse proxy
      ansible.builtin.import_role:
        name: traefik
      tags:
        - traefik

    - name: Set up nginx test page
      ansible.builtin.import_role:
        name: nginx_hello
      tags:
        - nginx_hello
        - hello

    - name: Set up unifi controller
      ansible.builtin.import_role:
        name: unifi
      tags:
        - unifi

    - name: Set up nextcloud
      ansible.builtin.import_role:
        name: nextcloud
      tags:
        - nextcloud

    - name: Set up zabbix
      ansible.builtin.import_role:
        name: zabbix
      tags:
        - zabbix
      when: false

    - name: Set up watchtower
      ansible.builtin.import_role:
        name: watchtower
      tags:
        - watchtower
      when: false

    - name: Set up netbox
      ansible.builtin.import_role:
        name: netbox
      tags:
        - netbox

    - name: Set up monitorss
      ansible.builtin.import_role:
        name: monitorss
      tags:
        - monitorss

    - name: Set up vaultwarden
      ansible.builtin.import_role:
        name: vaultwarden
      tags:
        - vaultwarden

    - name: Set up plex
      ansible.builtin.import_role:
        name: plex
      tags:
        - plex
      when: false

    - name: Set up transmission
      ansible.builtin.import_role:
        name: transmission
      tags:
        - transmission
      when: false

    - name: Set up servarr
      ansible.builtin.import_role:
        name: servarr
      tags:
        - servarr
      when: false

    # TODO: add separate traefik network

    # TODO: restructure playbook to not use raw docker containers

    # TODO: documentation for working on the playbook: folder structure, used ports etc.

    # TODO: health checks for services

    # TODO: automated testing

    # TODO: add dashboard (eg. Heimdall)

    # TODO: configure storage mounts

    # TODO: add authelia identity provider

    # TODO: add LDAP provider

    # TODO: add DDNS updater

    # TODO: add Hashicorp Vault

  post_tasks:
    - name: Prune unused images
      community.docker.docker_prune:
        images: true
