---

- name: Create data directories
  file:
    state: directory
    name: "{{ zabbix_dir }}/{{ item }}"
  with_items:
    - config # TODO: Find a better name for this (maybe something like `installation`?)
    - scripts
    - db

- name: Create zabbix shared network
  docker_network:
    name: zabbix_network

- name: MariaDB database container
  docker_container:
    name: zabbix-mariadb
    image: mariadb:10.5
    pull: true
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_bin"
    volumes:
      - "{{ zabbix_dir }}/db:/var/lib/mysql"
    env:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: "{{ zabbix_db_user }}"
      MYSQL_PASSWORD: "{{ zabbix_db_pass }}"
      MYSQL_ROOT_PASSWORD: "{{ zabbix_db_secret }}"
    networks:
      - name: zabbix_network
        aliases:
          - db
    network_mode: default
    restart_policy: unless-stopped
    container_default_behavior: compatibility

- name: Zabbix agent container
  docker_container:
    name: zabbix-agent
    image: zabbix/zabbix-agent:alpine-5.2-latest
    pull: true
    # ports:
    #   - "10050:10050"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - "{{ zabbix_dir }}/config/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro"
      - "{{ zabbix_dir }}/config/modules:/var/lib/zabbix/modules:ro"
      - "{{ zabbix_dir }}/config/enc:/var/lib/zabbix/enc:ro"
      - "{{ zabbix_dir }}/config/ssh_keys:/var/lib/zabbix/ssh_keys:ro"
    networks:
      - name: zabbix_network
    network_mode: default
    privileged: true
    restart_policy: unless-stopped
    container_default_behavior: compatibility

- name: Main server container
  docker_container:
    name: zabbix-server
    image: zabbix/zabbix-server-mysql:alpine-5.2-latest
    pull: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 
      - "{{ zabbix_dir }}/scripts/alertscripts:/usr/lib/zabbix/alertscripts:ro"
      - "{{ zabbix_dir }}/scripts/externalscripts:/usr/lib/zabbix/externalscripts:ro"
      - "{{ zabbix_dir }}/config/export:/var/lib/zabbix/export:rw"
      - "{{ zabbix_dir }}/config/modules:/var/lib/zabbix/modules:ro"
      - "{{ zabbix_dir }}/config/enc:/var/lib/zabbix/enc:ro"
      - "{{ zabbix_dir }}/config/ssh_keys:/var/lib/zabbix/ssh_keys:ro"
      - "{{ zabbix_dir }}/config/mibs:/var/lib/zabbix/mibs:ro"
      - "{{ zabbix_dir }}/config/snmptraps:/var/lib/zabbix/snmptraps:rw"
    env:
      DB_SERVER_HOST: db
      DB_SERVER_PORT: '3306'
      MYSQL_USER: "{{ zabbix_db_user }}"
      MYSQL_PASSWORD: "{{ zabbix_db_pass }}"
    networks:
      - name: zabbix_network
    network_mode: default
    restart_policy: unless-stopped
    container_default_behavior: compatibility

- name: SNMP traps container
  docker_container:
    name: zabbix-snmptraps
    image: zabbix/zabbix-snmptraps:alpine-5.2-latest
    pull: true
    ports:
    - "162:1162/udp"
    volumes:
    - "{{ zabbix_dir }}/config/snmptraps:/var/lib/zabbix/snmptraps"
    networks:
      - name: zabbix_network
    network_mode: default
    restart_policy: unless-stopped
    container_default_behavior: compatibility

- name: Front end container
  docker_container:
    name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:alpine-5.2-latest
    pull: true
    # ports:
    # - "80:8080"
    # - "443:8443"
    env:
      DB_SERVER_HOST: db
      DB_SERVER_PORT: '3306'
      MYSQL_USER: "{{ zabbix_db_user }}"
      MYSQL_PASSWORD: "{{ zabbix_db_pass }}"
    networks:
      - name: zabbix_network
    network_mode: default
    restart_policy: unless-stopped
    container_default_behavior: compatibility
    labels:
      traefik.enable: "true"
      traefik.http.routers.zabbix.rule: "Host(`zabbix.{{ homelab_domain }}`)"
      traefik.http.routers.zabbix.entrypoints: "websecure"
      traefik.http.routers.zabbix.tls: "true"
      traefik.http.services.zabbix.loadbalancer.server.port: "8080"
