---

- name: Create scheduled watchtower app container
  community.general.docker_container:
    name: watchtower-app
    image: containrrr/watchtower@sha256:6dd50763bbd632a83cb154d5451700530d1e44200b268a4e9488fefdfcf2b038
    hostname: "{{ ansible_hostname }}"
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env: "{{ watchtower_environment_variables }}"
    command: --monitor-only --schedule "{{ watchtower_schedule }}"
    restart_policy: unless-stopped
    container_default_behavior: compatibility
