---

name: CI
'on':
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.10'

      - name: Install linting dependencies
        run: pip install yamllint ansible-lint

      - name: Install external roles & collections for ansible-lint
        run: ansible-galaxy install -r ansible/requirements.yml

      - name: Lint all ansible playbooks in repo
        run: |
          echo "$VAULT_PASSWORD" > .vault_pass.txt
          export ANSIBLE_VAULT_PASSWORD_FILE=".vault_pass.txt"
          ansible-lint
        env:
          VAULT_PASSWORD: ${{secrets.VAULT_PASSWORD}}

      - name: Lint all yaml in repo
        run: yamllint .

      - name: Initialise Packer
        run: packer init .
        working-directory: packer

      - name: Validate Packer templates
        run: packer validate .
        working-directory: packer

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     # TODO: Come up with a more rigorous test setup
  #     - name: Pass
  #       run: echo 'Looks good to me 🤪'
