---

name: CI
'on':
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        ansible-lint-version:
          - '6.2.2'
          - '6.3.0'
          - '6.4.0'
          - '6.5.0'
          - '6.5.1'
          - '6.5.2'
          - '6.6.0'
          - '6.6.1'
          - '6.7.0'
          - '6.8.0'
          - '6.8.1'
          - '6.8.2'
          - '6.8.3'
          - '6.8.4'
          - '6.8.5'
          - '6.8.6'
          - '6.8.7'
          - '6.9.0'
          - '6.9.1'
          - '6.10.0'
          - '6.10.1'
          - '6.10.2'
          - '6.11.0'
          - '6.12.0'
          - '6.12.1'
          - '6.12.2'
          - '6.13.0'
          - '6.13.1'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install linting dependencies
        run: pip install yamllint ansible-lint==${{ matrix.ansible-lint-version }}

      - name: Install external roles for ansible-lint
        run: ansible-galaxy install -r ansible/requirements.yml

      - name: Lint ansible playbooks dir
        run: yamllint ansible/ && ansible-lint

      - name: Lint all yaml in repo
        run: yamllint .

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      # TODO: Come up with a more rigorous test setup
      # Will likely need to be run on the selfhosted runner
      - name: Pass
        run: echo 'Looks good to me 🤪'
