name: Build Packer templates

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 0 6 * * * # every day at 6am
  

jobs:
  build-ubuntu-2004:
    name: Build Ubuntu 20.04
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Packer
        uses: hashicorp-contrib/setup-packer@v1

      - name: Initialise Packer plugins
        run: packer init -upgrade .
        working-directory: ./packer
      
      - name: Validate Template
        run: packer validate -syntax-only .
        working-directory: ./packer

      - name: Build Template
        run: packer build -on-error=abort -force .
        working-directory: ./packer
        env:
          PKR_VAR_url: "${{ secrets.PROXMOX_URL }}"
          PKR_VAR_node: "${{ secrets.PROXMOX_NODE }}"
          PKR_VAR_username: "${{ secrets.PROXMOX_USERNAME }}"
          PKR_VAR_password: "${{ secrets.PROXMOX_PASSWORD }}"
