---

name: Terraform Plan & Apply
'on':
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

      - run: terraform fmt -check
      - run: terraform init
      - run: terraform validate -no-color
      - run: terraform plan -out=tfplan -var "do_token=${{secrets.DIGITALOCEAN_TOKEN}}"

      - name: Save Terraform plan for later
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: tfplan
          path: terraform/tfplan
          if-no-files-found: error


  apply:
    needs: plan
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

      - run: terraform init

      - name: Download plan
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: tfplan
          path: terraform/

      - run: terraform apply -auto-approve tfplan
