---

name: Terraform Plan & Apply
'on':
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

      - run: terraform fmt -check
      - run: terraform init
      - run: terraform validate -no-color
      - run: terraform plan -out=tfplan -var "do_token=${{secrets.DIGITALOCEAN_TOKEN}}"

      - name: Save Terraform plan for later
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: tfplan
          path: terraform/tfplan
          if-no-files-found: error


  apply:
    needs: plan
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

      - run: terraform init

      - name: Download plan
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
        with:
          name: tfplan
          path: terraform/

      - run: terraform apply -auto-approve tfplan
